### PR TITLE
Make the README example code more portable

### PR DESCRIPTION
**Pull request by SEJeff**
Also, the `$HOME` variable can be modified while `os.path.expanduser()` does the right thing.

This works on windows as well whereas the previous code did not.

### CODE REVIEW

**Comment by SEJeff** [comment]
I signed it!

**Comment by SEJeff** [comment]
If this seems sensible, I can change the actual code as well.

**Comment by mbohlool** [comment]
It does make sense. Please change example codes too and let me know when it is ready for review. Thanks for your contribution.

**Comment by SEJeff** [comment]
@mbohlool all you good sir. I figured I could start small contributing to some of the k8s ecosystem projects. Maybe I'll be able to help you grow this project to graduate out of the incubator.

**Comment by sebgoa** [comment]
lgtm

**Pull request merged**
