### PR TITLE
Add an in cluster config example

### PR DESCRIPTION
**Pull request by avinassh**
Saw a comment here about adding an in cluster config example - https://github.com/kubernetes-incubator/client-python/issues/255#issuecomment-308865095

### CODE REVIEW

**Comment by avinassh** [comment]
bump to verify the CLA

**Comment by avinassh** [comment]
bump to verify the CLA

**Comment by avinassh** [comment]
bump to verify the CLA

**Comment by avinassh** [comment]
bump to verify the CLA

**Comment by mbohlool** [comment]
looks good. please sign cla and add copyright header to the file. thanks.

**Comment by avinassh** [comment]
I have signed the CLA and I don't know why the bot is not picking it up :( 

I will add the copyright header

**Comment by mbohlool** [comment]
follow bot's troubleshooting steps at the end of its comment.

**Comment by avinassh** [comment]
Done 😄

**Comment by mbohlool** [comment]
Thanks for your contribution. keep it up :)

**Pull request merged**
