### PR TITLE
add examples for deployemt apps/v1beta2

### PR DESCRIPTION
**Pull request by chenhonggc**
add examples for deployemt apps/v1beta2

### CODE REVIEW

**Comment by chenhonggc** [comment]
@mbohlool  Is this PR worthwhile?

**Comment by tomplus** [comment]
It's almost identical to file `client-python/examples/deployment_examples.py`. Maybe we can mix them somehow...

**Comment by chenhonggc** [comment]
@tomplus  Thanks.

**Comment by tomplus** [comment]
No problem, I'm looking forward for updated version. Let me know if I can help ...

**Pull request closed without merging**
