### PR TITLE
Sync requirements and add license info

### LINKED ISSUE #131: No module named websocket in b2
Hello,

I install the client using pip and since b2 I've this error "No module named websocket".
Installing it manually works fine.

I've not much experience in python packaging etc... but it seems this dependency is missing from setup.py!

### PR DESCRIPTION
**Pull request by dims**
Follow guidelines in:
https://packaging.python.org/requirements/

* Make sure the same list of packages are in setup.cfg and
  requirements.txt
* install_requires reqs in setup.cfg should be "Abstract" with
  no version information
* Add License information for each package

Fixes #131

### CODE REVIEW

**Comment by mrmcmuffinz** [comment]
@dims Do we have to bump up the release version with these changes?

**Comment by dims** [comment]
@mrmcmuffinz : i'd vote to release another beta to make sure this works fine for folks who want to try it (cc @mbohlool)

**Comment by mbohlool** [comment]
@dims, this looks good. Can you add an entry in CHANGELOG in the same PR? I want to start requiring that for each PR to make sure we always have updated change log with correct references. I can do another release after this.

**Comment by mbohlool** [comment]
@dims, I didn't realize the release is broken, I will go ahead and add the changelog myself to do another release.

**Comment by mbohlool** [comment]
I've released 1.0.0b3. I think we should have an automated check for this to make sure it won't happen in future. Will add an issue for it.

**Pull request merged**
