### PR TITLE
Add notebook on how to create a ConfigMap and use its data in Pods

### PR DESCRIPTION
**Pull request by djkonro**

### CODE REVIEW

**Comment by sebgoa** [comment]
ok this is good.

Please add sentences before each code block to explain what the block is doing, otherwise this is just a script.

Once you add the documentation, you can remove the WIP from the PR

**Comment by sebgoa** [comment]
/lgtm 

looking much better

**Comment by sebgoa** [comment]
@mbohlool could you merge ?

**Comment by mbohlool** [comment]
Done.

**Pull request merged**
