### PR TITLE
 Add notebook on how to watch changes to an object 

### PR DESCRIPTION
**Pull request by djkonro**

### CODE REVIEW

**Comment by djkonro** [comment]
Work in process (WIP)

**Comment by sebgoa** [comment]
Sorry for the delay, you should add more information about what a watch is. Which resources can you watch ? etc.

Also the main issue here is that you only receive a fix amount of events and then exit. We need to figure out how to keep the stream open so that new events get received. It should not exit when the counter is 0.

**Comment by djkonro** [comment]
@sebgoa I have updated the notebook.

**Comment by sebgoa** [comment]
ok approved, a bit minimalist but ok.

/lgtm

**Pull request merged**
