### PR TITLE
add support for attach api call using websockets.

### PR DESCRIPTION
**Pull request by skuda**
Hi,

I needed to use /attach api call, this method exposes the same problem as /exec so I just reused the current solution using websockets.

### CODE REVIEW

**Comment by skuda** [comment]
Check CLA

**Comment by mbohlool** [comment]
LGTM. Thanks for the contribution.

**Comment by mbohlool** [comment]
nit: can you squash all commits into one please?

**Comment by skuda** [comment]
Done, sorry, someway 4 spaces where added to an empty line and I fixed it using the webinterface.

**Pull request merged**
