### PR TITLE
Remove code execution output from create_pod notebook

### PR DESCRIPTION
**Pull request by djkonro**

### CODE REVIEW

**Comment by djkonro** [comment]
@mbohlool, I am trying to use `replace_namespaced_pod(...)`, but when I execute the following lines
`pod.spec.containers[0].image = 'busybox:1.26.1'`
`v1.replace_namespaced_pod(name=name, namespace="default", body=pod)`
I get the error
`kubernetes.client.rest.ApiException: (422)`
`Reason: Unprocessable Entity`
`HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 25 Jun 2017 16:11:17 GMT', 'Content-`Length': '604', 'Content-Type': 'application/json'}) HTTP response body:` `{"kind":"Status","apiVersion":"v1","metadata":`{},"status":"Failure","message":"Pod \"busybox\" is` `invalid: spec: Forbidden: pod updates may not change fields other than `containers[*].image` or` ``spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing` `tolerations)","reason":"Invalid","details":{"name":"busybox","kind":"Pod","causes":` `[{"reason":"FieldValueForbidden","message":"Forbidden: pod updates may not change fields other` `than `containers[*].image` or `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to` `existing tolerations)","field":"spec"}]},"code":422}`

**Comment by mbohlool** [comment]
That look like a usecase for "patch" not "replace". Have you tried that?

**Comment by djkonro** [comment]
@mbohlool I was just trying to see how the "replace" command works with various object. I tried "patch" and it works fine for pods, and the "replace" command also works fine with ReplicationControllers and Deployments.

**Comment by mbohlool** [comment]
Please apply LGTM label to any PR that is ready to merge (also make sure the branch is up to date).

**Comment by sebgoa** [comment]
/lgtm

@mbohlool I don't think I have privs to add labels

**Pull request merged**
