### PR TITLE
Put whitespaces around equal sign on README

### PR DESCRIPTION
**Pull request by gabrielpjordao**

### CODE REVIEW

**Comment by mbohlool** [comment]
LGTM. please sign CLA.

**Comment by mbohlool** [comment]
LGTM. please sign CLA.

**Comment by gabrielpjordao** [comment]
Can you please verify if it has been signed correctly? Thanks!

**Comment by mbohlool** [comment]
yes the bot is confirming that. now you just need to rebase your branch with master.

**Comment by mbohlool** [comment]
actually it is fine. I can just merge it, the change is trivial. thanks.

**Pull request merged**
